#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Posicao {
    pub linha: u32,
    pub coluna: u32,
    pub deslocamento: usize,
}

#[derive(Debug, PartialEq, Clone)]
pub enum Simbolo<'a> {
    Number(i64, Posicao),
    Texto(&'a str, Posicao),
    Verdadeiro(Posicao),
    Falso(Posicao),
    Identificador(&'a str, Posicao),
    Variavel(Posicao),
    Importacao(Posicao),
    Se(Posicao),
    Senao(Posicao),
    SenaoSe(Posicao),
    Escolha(Posicao),
    Caso(Posicao),
    Padrao(Posicao),
    Enquanto(Posicao),
    Fazer(Posicao),
    Para(Posicao),
    ParaCada(Posicao),
    Sustar(Posicao),
    Continua(Posicao),
    Funcao(Posicao),
    Retorna(Posicao),
    Igual(Posicao),
    NaoIgual(Posicao),
    Menor(Posicao),
    Maior(Posicao),
    MenorIgual(Posicao),
    MaiorIgual(Posicao),
    E(Posicao),             
    Ou(Posicao),            
    Nao(Posicao),           
    Adicao(Posicao),
    Subtracao(Posicao),
    Multiplicacao(Posicao),
    Divisao(Posicao),
    Modulo(Posicao),         // % operator
    Potencia(Posicao),          // ** operator
    Incremento(Posicao),      // ++ operator
    Decremento(Posicao),      // -- operator
    Atribuir(Posicao),
    PontoEVirgula(Posicao),
    ParenteseEsquerdo(Posicao),
    ParenteseDireito(Posicao),
    ChaveEsquerda(Posicao),
    ChaveDireita(Posicao),
    ColcheteEsquerdo(Posicao),
    ColcheteDireito(Posicao),
    Virgula(Posicao),
    DoisPontos(Posicao),
    Ponto(Posicao),
    EOF(Posicao),
    Error(char, Posicao),
}
